# Generated by Django 3.2 on 2024-12-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20241215_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='appear_at',
            field=models.DateTimeField(verbose_name='дата и время появления'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='disappear_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время исчезновения'),
        ),
    ]
